### ISSUE TITLE
Formulario. Centro de Acopio

### ISSUE THREAD

**Issue by sofgarya** [miguelsalazar/mapeo_colaborativo#17]
Evaluar la opción de meter coordenadas x,y    si el número del sitio no se sabe.

Ejemplo: He metido un centro de acopio del cual me mandaron sus coordenadas, está el Estado, Municipio, Localidad, Calle pero no tiene número. Este centro de acopio es importante porque está en una de las localidades afectadas.

Por lo tanto, sería bueno tener la opción de si no se cuenta con el número, con meter las coordenadas sería perfecto.

**Comment by leodc** [comment]
Hola @sofgarya ! gracias por tu comentario, para todo lo referente a levantamiento de datos vamos a estar colaborando con #Verifica19s puedes comenzar a hablar con ellos sobre la necesidad de los campos :)? [horizonalmx](https://twitter.com/horizontalmx)
