### ISSUE TITLE
Agregar el tipo de ayuda en el formulario

### ISSUE THREAD

**Issue by neodevelop** [miguelsalazar/mapeo_colaborativo#2]
Agregar opciones predefinidas: 
Camiones
Grúas
Excavadoras
Sierras
Gato hidráulico
Diésel
Planta de energía
Lámpara
Picos
Palas
Cuerdas
Arneses
Sanitarios portátiles
Lonas
Comida
Medicinas y material de curación
Otros (con opción para escribir)

**Comment by acoronadoiruegas** [comment]
Complementar la información y ser muy específicos en el tipo de ayuda requerida, se sugiere incluir los siguientes campos:

- Requerimientos:
- Revisión del inmueble  Si/NO 
- Materiales y suministros Si/NO 
-Cuántos:
-Camiones
-Grúas
-Excavadoras
-Sierras
-Gato hidráulico
-Diesel
-Planta de energía
-Lámpara
-Picos
-Palas
-Cuerdas
-Arneses
-Sanitarios portátiles
-Lonas
-Comida
-Medicinas y material de curación
-Otros
-Voluntarios

**Comment by leodc** [comment]
El input debe de ser de selección multiple y además si se selecciona "otro" debe crear un campo de texto para las opciones que estén fuera, así se podría seleccionar "Cuerda, Sierras, Comida para perro y toallas sanitarias"

**Comment by Titopsky** [comment]
Claro también se requiere especificar el tipo de inmueble:
Vivienda, comercio, escuela, institución pública
O edificio de gobierno...

**Comment by leodc** [comment]
Para todo lo referente con levantamiento de datos vamos a colaborar con #Verificado19s
