### ISSUE TITLE
Encabezados no corresponden para todos los datos descargados

### ISSUE THREAD

**Issue by animalito** [miguelsalazar/mapeo_colaborativo#23]
Los datos aplanados en csv tienen algunos errores en la asignación de encabezados.

![image](https://user-images.githubusercontent.com/4116697/31098263-9f8886ca-a787-11e7-9eb6-a60b1e9d8d77.png)
 
Supongo que tiene que ver con la fuente.

¿Además, se podría agregar el dato de la fuente?

**Comment by leodc** [comment]
Hola ! gracias por el reporte ! habia un problema en el algoritmo de como se construyen los archivos, ya quedo arreglado junto con el nuevo campo donde se especifica la fuente.

Saludos !
