### ISSUE TITLE
La barra superior no funciona bien en Edge

### ISSUE THREAD

**Issue by alex-mayorga** [miguelsalazar/mapeo_colaborativo#3]
¡Hola!

Los botones de zoom no son visisbles.
![imagen](https://user-images.githubusercontent.com/649262/30688996-42feae1c-9e85-11e7-8d8c-ff84bbee416b.png)

¡Gracias!

**Comment by leodc** [comment]
Hola ! se arreglo el error y se subirá en el siguiente update, 

Saludos !
