### ISSUE TITLE
Mejorar la integración de la capa de Mapillary

### ISSUE THREAD

**Issue by ccossio** [miguelsalazar/mapeo_colaborativo#4]
La idea es aplicar la libreria de MapillaryJS para que se vean mejor las imagenes 360.

**Comment by ccossio** [comment]
Aqui esta el codigo que se va a implementar.

https://github.com/cbeddow/cbeddow.github.io/tree/master/bsas

**Comment by hectorbenitez** [comment]
Trabajando en este issue

**Comment by leodc** [comment]
Resuelto en hectorbenitez@8462c09a8c003eb1653abdc98f8f7362ea522f55
