### ISSUE TITLE
Agregar tipo de inmueble en el formulario 

### ISSUE THREAD

**Issue by Titopsky** [miguelsalazar/mapeo_colaborativo#5]
Se requiere agregar tipo de inmueble en el formulario
tipo de inmueble :escuelas, hospitales, comercio, iglesias (debido a que Puebla presenta una gran cantidad de construcciones de este tipo), instituciónes públicas o de gobierno
También considerar si ya fueron revisadas y considerar si presenta daños estructurales no sugiero agregar si es habitable o no al. Menos que no se pueda visualizar por el asunto de seguridad

**Comment by leodc** [comment]
Hola @Titopsky, para todo lo referente con levantamiento de datos vamos a estar colaborando con #Verificado19s en el mapa puedes encontrar unas ligas a los formularios y cualquier duda o comentario sobre estos lo puedes checar con [horizontalmx](https://twitter.com/horizontalmx)

**Comment by Titopsky** [comment]
Existe un problema en el. Formulario no aparece chiapas y tampoco oaxaca,
hay agregar incluso algunas áreas de Veracruz y tabasco.

En cuanto a la evaluación de daños hay un formato que se apega a las normas
de construcción

https://docs.google.com/forms/d/e/1FAIpQLScPjTQGuSpA6yupVD0-QdGr0lYiePk9ICj93MSjYsWFoXlRGA/viewform


Si te vas a la sección de edificios dañados así es como lo marca por el
momento protección civil,  no es todo el formato que te adjunto solo se
consideran por el tiempo, espero sirva e algo la aportacion
