### ISSUE TITLE
Capa. Centro de acopio

### ISSUE THREAD

**Issue by sofgarya** [miguelsalazar/mapeo_colaborativo#6]
¿Alguien puede decirme donde agregar centros de acopio? No encuentro de donde obtiene la información y urge agregar todos los centros de acopio al menos de mi ciudad.

He abierto hasta esto:
https://docs.google.com/spreadsheets/d/1vHrM6r3sO1f6ylsci_B7z08PrLsYKpG5VywjZXD6l5M/edit#gid=143622177

Estoy como loca viendo el código fuente. 

GRACIAS

**Comment by leodc** [comment]
Sobre el mapa se pusieron unos links que llevan a los formularios de #Verificado19s para agregar nueva información :) !
