### ISSUE TITLE
Opciones en Tipo de daño

### ISSUE THREAD

**Issue by sofgarya** [miguelsalazar/mapeo_colaborativo#9]
Tengo información de lugares afectados, que no necesariamente tiene información si hay derrumbe, fuga de gas, etc., por lo que no puedo levantar un informe ya que por default viene el TIPO DE DAÑO ¿Sería posible poner un valor de tipo "otro"? 

Por ejemplo en una localidad de Morelos necesitan voluntarios para remover escombros. Si subo un reporte con el valor por default aparecerá como derrumbe y será información INCORRECTA.

**Comment by ricardoricho** [comment]
Esta en #15
